### ISSUE TITLE
Panic when with target wasm32-wasi

### ISSUE THREAD

**Issue by sonhal** [jedisct1/rust-coarsetime#15]
Hi i am using the https://github.com/jedisct1/rust-jwt-simple library for my Envoy wasm filter. I am using wasm32-wasi as a target. Seems like this library panics when getting the current time with:   

`[source/extensions/common/wasm/context.cc:1180] wasm log: panicked at 'Clock not available: Error { code: 58, name: "NOTSUP", message: "Not supported, or operation not supported on socket." }', /Users/sondre/.cargo/registry/src/github.com-1ecc6299db9ec823/coarsetime-0.1.18/src/instant.rs:164:67
`

Are you aware of this issue with the wasm32-wasi target?

**Comment by sonhal** [comment]
Checked, and it works with `CLOCKID_REALTIME`, since the tokens usually are received from over the network, is it really necessary with a monotonic clock?

**Comment by jedisct1** [comment]
Looks like this is something that the runtime doesn't implement.

What WebAssembly runtime is it?

**Comment by sonhal** [comment]
Sorry @jedisct1, it was indeed the runtime: https://github.com/proxy-wasm/proxy-wasm-rust-sdk/issues/103

**Comment by sonhal** [comment]
Your a god damn champ @jedisct1 🎉  I think you just saved a big part of my thesis work :)
