### ISSUE TITLE
Expose from_u64 and as_u64 APIs?

### ISSUE THREAD

**Issue by nmathewson** [jedisct1/rust-coarsetime#17]
Hello!

I have a use in case where I need to update an atomic timer every time a given event occurs.  To do that, I'm using an `AtomicU64`, and `coarsetime::Instant::as_u64()`.  That latter API is not publicly documented, however, which implies that it might go away in the future.

Would you be open to a patch that would document and stabilize the APIs that convert Instant and Duration values to and from u64?  Or if you think that's a bad idea, would you be open to a patch to add an AtomicInstant type?

**Comment by jedisct1** [comment]
Hi Nick,

This is an internal representation. Users may think that `as_u64()` returns a number of milliseconds or some other standard unit, but this is not the case.

Maybe call it `ticks` or something similar in order to make that clear?

**Comment by nmathewson** [comment]
`as_ticks` and `from_ticks` would work fine for me; want me to write a patch?

**Comment by jedisct1** [comment]
A new release should now be on crates.io :)
