### ISSUE TITLE
Raw API for getting Instant::now without updating/reading cache

### ISSUE THREAD

**Issue by orlp** [jedisct1/rust-coarsetime#19]
As far as I can see there is no way to get the current instant without interacting with the `RECENT` cache (load or store). It would be nice to add that. I have no intention of using the cache but `Instant::now()` does a useless atomic relaxed store on every call.

Essentially, I'm asking to have `Instant::_now` be exposed in the public API (under a better name, of course).

**Comment by jedisct1** [comment]
Sure! Do you have a name to suggest for that function?

**Comment by orlp** [comment]
Maybe `Instant::now_raw` or `Instant::now_noupdate`?
