### ISSUE TITLE
Runtime errors in wasm32-freestanding

### ISSUE THREAD

**Issue by amiller68** [jedisct1/rust-coarsetime#25]
PROBLEM:
coarsetime v0.1.28 relies on an implementation of time that is not supported in all WASM environments (I haven't tested node, but I produced this issue within a browser runtime)

At runtime you get errors that look like:

```
    error output:
        panicked at library/std/src/sys/wasm/../unsupported/time.rs:31:9:
        time not implemented on this platform
```

SOLUTION:
I was able to get my code compiling and tests passing by specifying:

```
jwt-simple = "0.11.6"
coarsetime = { version = "=0.1.23" }
```

OBSERVATIONS:
I also confirmed that setting 

```
jwt-simple = "0.11.6"
```

and coarsetime to 1.27, 1.26, 1.25, or 1.24 doesn't compile.

TAKEAWAYS:
Therefore I am fairly confident at v0.11.7 just doesn't work in (at the very least) the browser, no matter how you configure coarsetime; and that v0.11.6 was the last viable version for using this library in wasm, so long as you set:

```
coarsetime = "=0.1.23"
```

SUGGESTIONS:

1.
yank v0.11.7 and in v0.11.6 specify

```
coarsetime = "=0.1.23"
```

not 

```
coarsetime = "^0.1.23"
```

in the Cargo.toml

2.
If you advertise WASM compatibility in your docs:

> jwt-simple uses only pure Rust implementations, and can be compiled out of the box to WebAssembly/WASI

write tests that compile to and run within a WASM runtime.

**Comment by jedisct1** [comment]
Can you check if 563841866bc0d0e5b8e1edf58e3918b43b11044c fixes your issue?

Completely untested as I didn't manage to run the tests for that target.

**Comment by amiller68** [comment]
Yep! Thank you :)
