### ISSUE TITLE
`time` crate conversion slower on some platforms

### ISSUE THREAD

**Issue by dragazo** [jedisct1/rust-coarsetime#26]
I was considering using this crate for faster time lookups since I'm writing a language runtime that has some nontrivial time-based scheduling logic. I need sub-millisecond precision, so I can't actually use the coarse/recent time features in this crate, but this crate also claimed to have faster lookups of the real current time. Specifically I need to create an instance of the `OffsetDateTime` type from the no-std compatible `time` crate. But it looks like using this crate as the time source is actually slower on some platforms:

```rs
#![feature(test)]

use time::{OffsetDateTime, UtcOffset};

pub fn old_way(utc_offset: UtcOffset) -> OffsetDateTime {
    OffsetDateTime::now_utc().to_offset(utc_offset)
}
pub fn new_way(utc_offset: UtcOffset) -> OffsetDateTime {
    let t = coarsetime::Clock::now_since_epoch();
    OffsetDateTime::from_unix_timestamp_nanos(t.as_nanos() as i128).unwrap()
}

#[cfg(test)]
mod tests {
    use crate::*;
    extern crate test;
    use test::{Bencher, black_box};

    #[bench]
    fn bench_old_way(b: &mut Bencher) {
        b.iter(|| {
            black_box(old_way(UtcOffset::UTC));
        });
    }

    #[bench]
    fn bench_new_way(b: &mut Bencher) {
        b.iter(|| {
            black_box(new_way(UtcOffset::UTC));
        });
    }
}

```

And I got the following results on raspberry pi:

```txt
running 2 tests
test tests::bench_new_way ... bench:       1,326 ns/iter (+/- 6)
test tests::bench_old_way ... bench:         527 ns/iter (+/- 4)
```

I realize this isn't this crate's fault, rather the combined behavior of the two, but is there some more efficient way to go about this specific use case? Or, since it's practically the de-facto standard, can support for the `time` crate be added in this crate as an optional feature to bypass some of the inefficiencies in the conversion?

**Comment by jedisct1** [comment]
On most platforms, `Clock::now_since_epoch()` just calls `std::time::SystemTime::now()`. It used to be faster, using the monotonic clock, but eventually went down to simply using this function.

This is slow, but some hosts have completely broken clock that `ntpd`-like damons keep adjusting, so optimizations have to be disabled to get the adjusted values.

`coarsetime` is great if you need times and instants to be cached, or if you need a stable API.
