### ISSUE TITLE
thread sleep 1ns，instant.elapsed().as_nanos() result = 0

### ISSUE THREAD

**Issue by DestinyL** [jedisct1/rust-coarsetime#36]
use std::time::Instant，same function，≈50u(meet expectations)；but，use coarsetime::Instant，result always 0.

so，design like this？

Indeed, it was very fast. I simply verified it.

**Comment by DestinyL** [comment]
`let instant = Instant::now();
    std::thread::sleep(std::time::Duration::from_nanos(1));
    println!("{}", instant.elapsed().as_nanos());`

**Comment by jedisct1** [comment]
Yes, this gives you a coarse timestamp.
