### ISSUE TITLE
Potentially replace AtomicU64

### ISSUE THREAD

**Issue by dragostis** [jedisct1/rust-coarsetime#6]
Since 64 bit stores on 32 bit machines may not be atomic, the use of `AtomicU64` is mandated, but a potential solution to the issue of nightly requirement could be using [`AtomicOption`](https://docs.rs/crossbeam/0.3.0/crossbeam/sync/struct.AtomicOption.html) instead.

**Comment by dragostis** [comment]
Does this idea sound good? I could start working on a PR with this change. This would also remove the need for the mutex and the compile feature.

**Comment by jedisct1** [comment]
Sounds good! If `AtomicOption` is equivalent to a cmpxchg of a pointer, there should be no performance impact.

**Comment by dragostis** [comment]
I gave `AtomicOption`'s code a read and it seems like it's doing heap reallocations, so there will be a penalty in performance. However, it's still quite annoying since a simple store should not affect atomicity.

**Comment by dragostis** [comment]
I've worked a [solution](https://play.rust-lang.org/?gist=d4f76e48227bb25a09312ff4a8b06961&version=stable) that I'm pretty satisfied with. It's similar to `AtomicOption`, the difference being that it recycles heap allocations.

**Comment by jedisct1** [comment]
This is very neat.

**Comment by dragostis** [comment]
This doesn't work, unfortunately. 😞 The issue is that `_update` can be called from multiple thread, so mutating the cached `Box` is unsafe. Seems like there's no way to get around the allocation unless every thread has its own cached `Box`, but I'm not sure this can be done with Rust.

**Comment by jedisct1** [comment]
:(

**Comment by dragostis** [comment]
Could you please publish a new version? (I would recommend bumping to `0.2.0` just in case there will be issues)
