### ISSUE TITLE
Use std::time::Duration?

### ISSUE THREAD

**Issue by breeswish** [jedisct1/rust-coarsetime#8]
Looks like the `Duration` introduced by this crate can be replaced by `std::time::Duration` instead. There is no extra cost when the user does not use the Duration.

**Comment by jedisct1** [comment]
Oh no, there's not the same. Coarsetime's duration encodes timestamps as a `u64` (the unit is 1/2^32 second) to be fast. Using `std::time::Duration` instead would be slow.
